# Generated by Django 5.0.3 on 2024-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebApp', '0003_infopng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPng',
        ),
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
