# Generated by Django 5.0.3 on 2024-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebApp', '0005_cusubmission_alter_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WfmAnonContactsubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CUsubmission',
        ),
    ]
