# Generated by Django 5.0.3 on 2024-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
